# Generated by Django 5.2 on 2025-04-25 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='seats_booked',
            new_name='seats',
        ),
    ]
